<?php

/* vim: set expandtab tabstop=4 shiftwidth=4 softtabstop=4: */

/**
 * Staging table databse functions
 *
 * PHP version 5.3
 *
 * @author     PMBliss <pmbliss@retaildimensions.com>
 * @copyright  2005-2015 Retail Dimensions Inc.
 * @version    1.0.0
 */
class rdi_pos_install extends rdi_install 
{    
    
    public static $pos_tables = array(
"rpro_in_categories" => "CREATE TABLE `rpro_in_categories` (
  `catalog_id` int(11) NOT NULL,
  `site_id` int(11) DEFAULT NULL,
  `parent_id` int(11) DEFAULT NULL,
  `category` varchar(255) DEFAULT NULL,
  `description` mediumtext,
  `sort_order` int(11) DEFAULT NULL,
  `meta_description` mediumtext,
  `meta_keywords` mediumtext,
  `meta_title` varchar(255) DEFAULT NULL,
  `image_path` varchar(255) DEFAULT NULL,
  `level` int(10) DEFAULT NULL,
  `published` varchar(10) DEFAULT 1,
  PRIMARY KEY (`catalog_id`),
  KEY `site_id` (`site_id`),
  KEY `parent_id` (`parent_id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8",

"rpro_in_category_products" => "CREATE TABLE `rpro_in_category_products` (
  `catalog_id` int(11) NOT NULL,
  `style_sid` varchar(64) NOT NULL,
  `sort_order` int(11) DEFAULT NULL,
  `date_added` varchar(64) DEFAULT NULL,
  PRIMARY KEY (`catalog_id`,`style_sid`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC",

"rpro_in_gift_reg" => "CREATE TABLE `rpro_in_gift_reg` (
  `sid` varchar(50) CHARACTER SET latin1 DEFAULT NULL,
  `sbs_no` varchar(50) CHARACTER SET latin1 DEFAULT NULL,
  `store_no` varchar(10) CHARACTER SET latin1 DEFAULT NULL,
  `so_no` varchar(50) CHARACTER SET latin1 DEFAULT NULL,
  `so_doc_no` varchar(50) CHARACTER SET latin1 DEFAULT NULL,
  `so_type` varchar(10) CHARACTER SET latin1 DEFAULT NULL,
  `shipto_cust_sid` varchar(50) CHARACTER SET latin1 DEFAULT NULL,
  `status` varchar(10) CHARACTER SET latin1 DEFAULT NULL,
  `created_date` varchar(30) CHARACTER SET latin1 DEFAULT NULL,
  `modified_date` varchar(30) CHARACTER SET latin1 DEFAULT NULL,
  `cancel_date` varchar(30) CHARACTER SET latin1 DEFAULT NULL,
  `instruction1` varchar(60) CHARACTER SET latin1 DEFAULT NULL,
  `instruction2` varchar(60) CHARACTER SET latin1 DEFAULT NULL,
  `instruction3` varchar(60) CHARACTER SET latin1 DEFAULT NULL,
  `instruction4` varchar(60) CHARACTER SET latin1 DEFAULT NULL,
  `instruction5` varchar(60) CHARACTER SET latin1 DEFAULT NULL,
  `item_sid` varchar(30) CHARACTER SET latin1 DEFAULT NULL,
  `item_price` decimal(12,4) DEFAULT NULL,
  `qty_shipped` int(10) DEFAULT NULL,
  `item_ext_price` decimal(12,4) DEFAULT NULL,
  `item_orig_price` decimal(12,4) DEFAULT NULL,
  `item_tax` decimal(12,4) DEFAULT NULL,
  KEY `idx_sid` (`sid`),
  KEY `idx_item_sid` (`item_sid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8",

"rpro_in_customers" => "CREATE TABLE `rpro_in_customers` (
  `fldcustsid` varchar(50) DEFAULT NULL,
  `fldtitle` varchar(50) DEFAULT NULL,
  `fldfname` varchar(50) DEFAULT NULL,
  `fldlname` varchar(50) DEFAULT NULL,
  `fldcompany` varchar(100) DEFAULT NULL,
  `fldaddr1` varchar(50) DEFAULT NULL,
  `fldaddr2` varchar(50) DEFAULT NULL,
  `fldaddr3` varchar(50) DEFAULT NULL,
  `fldzip` varchar(50) DEFAULT NULL,
  `fldphone1` varchar(50) DEFAULT NULL,
  `fldphone2` varchar(50) DEFAULT NULL,
  `fldcustid` varchar(50) DEFAULT NULL,
  `web_cust_sid` varchar(50) DEFAULT NULL,
  `email` varchar(100) DEFAULT NULL,
  `fldprclvl` varchar(50) DEFAULT NULL,
  `fldprclvl_i` varchar(50) DEFAULT NULL
) ENGINE=MyISAM DEFAULT CHARSET=utf8",

"rpro_in_images" => "CREATE TABLE `rpro_in_images` (
  `style_sid` varchar(64) CHARACTER SET utf8 NOT NULL DEFAULT '',
  `attr_code` varchar(255) CHARACTER SET utf8 DEFAULT NULL,
  `type` varchar(10) DEFAULT NULL,
  `image` varchar(100) CHARACTER SET utf8 DEFAULT NULL,
  `sort` int(10) DEFAULT '0',
  KEY `style_sid` (`style_sid`),
  KEY `attr_code` (`attr_code`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8",

"rpro_in_items" => "CREATE TABLE `rpro_in_items` (
  `style_sid` varchar(64) NOT NULL DEFAULT '',
  `item_sid` varchar(64) NOT NULL DEFAULT '',
  `item_num` varchar(16) DEFAULT '0',
  `alu` varchar(128) DEFAULT NULL,
  `upc` varchar(128) DEFAULT NULL,
  `ship_weight1` decimal(10,4) DEFAULT NULL,
  `ship_weight2` decimal(10,4) DEFAULT NULL,
  `oversized` int(1) DEFAULT '0',
  `ship_method` varchar(16) DEFAULT NULL,
  `featured` int(1) DEFAULT '0',
  `height` varchar(16) DEFAULT NULL,
  `length` varchar(16) DEFAULT NULL,
  `width` varchar(16) DEFAULT NULL,
  `dim_unit` varchar(64) DEFAULT NULL,
  `weight_unit` varchar(64) DEFAULT NULL,
  `desc3` varchar(50) DEFAULT NULL,
  `desc4` varchar(50) DEFAULT NULL,
  `text1` varchar(255) DEFAULT NULL,
  `text2` varchar(255) DEFAULT NULL,
  `text3` varchar(255) DEFAULT NULL,
  `text4` varchar(255) DEFAULT NULL,
  `text5` varchar(255) DEFAULT NULL,
  `text6` varchar(255) DEFAULT NULL,
  `text7` varchar(255) DEFAULT NULL,
  `text8` varchar(255) DEFAULT NULL,
  `text9` varchar(255) DEFAULT NULL,
  `text10` varchar(255) DEFAULT NULL,
  `udf_date` varchar(64) DEFAULT NULL,
  `udf_name` varchar(255) DEFAULT NULL,
  `udf1` varchar(255) DEFAULT NULL,
  `udf2` varchar(255) DEFAULT NULL,
  `udf3` varchar(255) DEFAULT NULL,
  `udf4` varchar(255) DEFAULT NULL,
  `udf5` varchar(255) DEFAULT NULL,
  `udf6` varchar(255) DEFAULT NULL,
  `udf7` varchar(255) DEFAULT NULL,
  `udf8` varchar(255) DEFAULT NULL,
  `udf9` varchar(255) DEFAULT NULL,
  `udf10` varchar(255) DEFAULT NULL,
  `udf11` varchar(255) DEFAULT NULL,
  `udf12` varchar(255) DEFAULT NULL,
  `udf13` varchar(255) DEFAULT NULL,
  `udf14` varchar(255) DEFAULT NULL,
  `image1` varchar(100) DEFAULT NULL,
  `image2` varchar(100) DEFAULT NULL,
  `image3` varchar(100) DEFAULT NULL,
  `image4` varchar(100) DEFAULT NULL,
  `image5` varchar(100) DEFAULT NULL,
  `image6` varchar(100) DEFAULT NULL,
  `image7` varchar(100) DEFAULT NULL,
  `image8` varchar(100) DEFAULT NULL,
  `image9` varchar(100) DEFAULT NULL,
  `image10` varchar(100) DEFAULT NULL,
  `attr` varchar(255) DEFAULT NULL,
  `attr_code` varchar(255) DEFAULT NULL,
  `size` varchar(255) DEFAULT NULL,
  `size_code` varchar(255) DEFAULT NULL,
  `attr_order` varchar(16) DEFAULT NULL,
  `size_order` varchar(16) DEFAULT NULL,
  `cost` decimal(10,2) DEFAULT NULL,
  `price` decimal(10,2) DEFAULT NULL,
  `markdown_price` decimal(10,2) DEFAULT NULL,
  `reg_price` decimal(10,2) DEFAULT NULL,
  `sale_price` decimal(10,2) DEFAULT NULL,
  `msrp_price` decimal(10,2) DEFAULT NULL,
  `wholesale_price` decimal(10,2) DEFAULT NULL,
  `quantity` int(11) DEFAULT '0',
  `so_committed` int(11) DEFAULT '0',
  `open_po` int(11) DEFAULT '0',
  `comp_quantity` int(11) DEFAULT '0',
  `qty_per_case` int(11) DEFAULT '0',
  `tax_code` varchar(16) DEFAULT NULL,
  `active` int(1) DEFAULT '1',
  `excluded` int(1) DEFAULT '0',
  PRIMARY KEY (`style_sid`,`item_sid`),
  KEY `style_sid` (`style_sid`),
  KEY `item_sid` (`item_sid`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC",

"rpro_in_priceqty" => "CREATE TABLE `rpro_in_priceqty` (
  `style_sid` varchar(64) CHARACTER SET utf8 NOT NULL DEFAULT '',
  `item_sid` varchar(64) CHARACTER SET utf8 NOT NULL DEFAULT '',
  `quantity` int(11) DEFAULT '0',
  `open_po` int(11) DEFAULT '0',
  `so_committed` int(11) DEFAULT '0',
  `reg_price` decimal(10,2) DEFAULT NULL,
  `price` decimal(10,2) DEFAULT NULL,
  `sale_price` decimal(10,2) DEFAULT NULL,
  `markdown_price` decimal(10,2) DEFAULT NULL,
  `msrp_price` decimal(10,2) DEFAULT NULL,
  `wholesale_price` decimal(10,2) DEFAULT NULL,
  `cost` decimal(10,2) DEFAULT NULL
) ENGINE=MyISAM DEFAULT CHARSET=utf8",

"rpro_in_receipts" => "CREATE TABLE `rpro_in_receipts` (
  `so_number` varchar(50) DEFAULT NULL,
  `receipt_number` varchar(50) DEFAULT NULL,
  `receipt_sid` varchar(50) DEFAULT NULL,
  `storestation` varchar(50) DEFAULT NULL,
  `receipt_date` varchar(50) DEFAULT NULL,
  `receipt_subtotal` varchar(50) DEFAULT NULL,
  `receipt_shipamount` varchar(50) DEFAULT NULL,
  `receipt_feeamount` varchar(50) DEFAULT NULL,
  `receipt_taxarea` varchar(50) DEFAULT NULL,
  `receipt_totaltax` varchar(50) DEFAULT NULL,
  `receipt_total` varchar(50) DEFAULT NULL,
  `receipt_item_number` varchar(50) DEFAULT NULL,
  `sid` varchar(50) DEFAULT NULL,
  `qty` varchar(50) DEFAULT NULL,
  `extprc` varchar(50) DEFAULT NULL,
  `extpwt` varchar(50) DEFAULT NULL
) ENGINE=MyISAM DEFAULT CHARSET=utf8",

"rpro_in_return" => "CREATE TABLE `rpro_in_return` (
  `so_number` varchar(50) DEFAULT NULL,
  `so_doc_no` varchar(50) DEFAULT NULL,
  `invc_sid` varchar(50) DEFAULT NULL,
  `invc_no` varchar(50) DEFAULT NULL,
  `disc_amt` decimal(10,4) DEFAULT NULL COMMENT 'Amount of all items less taxes',
  `shipping` decimal(10,4) DEFAULT NULL COMMENT 'Amount of Shipping',
  `comment1` text,
  `comment2` text,
  `refund_date` varchar(50) DEFAULT NULL,
  `item_qty_returned` double DEFAULT NULL,
  `item_qty_ordered` double DEFAULT NULL,
  `item_sid` varchar(50) DEFAULT NULL,
  `item_alu` varchar(50) DEFAULT NULL COMMENT 'Secondary product identification.',
  `item_price` double DEFAULT NULL,
  `record_type` varchar(25) DEFAULT NULL COMMENT 'refund or item type'
) ENGINE=MyISAM DEFAULT CHARSET=utf8",

"rpro_in_so" => "CREATE TABLE `rpro_in_so` (
  `so_number` varchar(50) DEFAULT NULL,
  `so_doc_no` varchar(50) DEFAULT NULL,
  `sid` varchar(50) DEFAULT NULL,
  `invc_no` varchar(50) DEFAULT NULL,
  `status` varchar(50) DEFAULT NULL,
  `tender_amt` double DEFAULT NULL,
  `subtotal` double DEFAULT NULL,
  `tax_total` double DEFAULT NULL,
  `fee_amt` double DEFAULT NULL,
  `fee_type` varchar(50) DEFAULT NULL,
  `disc_amt` double DEFAULT NULL,
  `capture_fund` varchar(50) DEFAULT NULL,
  `qty_shipped` double DEFAULT NULL,
  `ship_date` varchar(50) DEFAULT NULL,
  `item_sid` varchar(50) DEFAULT NULL,
  `item_number` varchar(50) DEFAULT NULL,
  `item_tax` double DEFAULT NULL,
  `item_orig_price` double DEFAULT NULL,
  `item_ext_price` double DEFAULT NULL,
  `item_price` double DEFAULT NULL,
  `item_qty` double DEFAULT NULL,
  `tracking_number` varchar(100) DEFAULT NULL,
  `shipprovider` varchar(100) DEFAULT 'UPS',
  `cancel_date` varchar(100) DEFAULT NULL,
  KEY `so_number` (`so_number`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8",

"rpro_in_store" => "CREATE TABLE `rpro_in_store` (
  `store_code` varchar(5) NOT NULL,
  `store_name` varchar(50) DEFAULT NULL,
  `address1` varchar(150) DEFAULT NULL,
  `address2` varchar(150) DEFAULT NULL,
  `zip` varchar(10) DEFAULT NULL,
  PRIMARY KEY (`store_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8",

"rpro_in_store_qty" => "CREATE TABLE `rpro_in_store_qty` (
  `style_sid` varchar(30) DEFAULT NULL,
  `item_sid` varchar(30) DEFAULT NULL,
  `store_code` varchar(10) DEFAULT NULL,
  `quantity` int(11) DEFAULT '0',
  `so_committed` int(11) DEFAULT '0',
  KEY `idx_style_sid` (`style_sid`),
  KEY `idx_item_sid` (`item_sid`),
  KEY `idx_store_code` (`store_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8",

"rpro_in_styles" => "CREATE TABLE `rpro_in_styles` (
  `style_sid` varchar(64) NOT NULL DEFAULT '',
  `scale` int(6) DEFAULT NULL,
  `scale_name` varchar(64) DEFAULT NULL,
  `dcs` varchar(64) DEFAULT NULL,
  `dcs_name` varchar(128) DEFAULT NULL,
  `department_code` varchar(12) DEFAULT NULL,
  `department_name` varchar(64) DEFAULT NULL,
  `class_code` varchar(12) DEFAULT NULL,
  `class_name` varchar(64) DEFAULT NULL,
  `subclass_code` varchar(12) DEFAULT NULL,
  `subclass_name` varchar(64) DEFAULT NULL,
  `vendor_code` varchar(60) DEFAULT NULL,
  `vendor` varchar(255) DEFAULT NULL,
  `vend_info1` varchar(255) DEFAULT NULL,
  `vend_info2` varchar(255) DEFAULT NULL,
  `desc1` varchar(255) DEFAULT NULL,
  `desc2` varchar(255) DEFAULT NULL,
  `desc3` varchar(255) DEFAULT NULL,
  `desc4` varchar(255) DEFAULT NULL,
  `eci` int(6) DEFAULT '0',
  `long_desc` text,
  `product_name` varchar(200) DEFAULT NULL,
  `alt1_desc` text,
  `alt2_desc` text,
  `meta_title` varchar(200) DEFAULT NULL,
  `meta_keywords` varchar(500) DEFAULT NULL,
  `meta_desc` tinytext,
  `threshold` decimal(10,2) DEFAULT NULL,
  `avail` varchar(50) DEFAULT NULL,
  `out_of_stock_msg` varchar(100) DEFAULT NULL,
  `style_image` varchar(64) DEFAULT NULL,
  PRIMARY KEY (`style_sid`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8",

"rpro_in_upsell_item" => "CREATE TABLE `rpro_in_upsell_item` (
  `style_sid` varchar(50) DEFAULT NULL,
  `upsell_sid` varchar(50) DEFAULT NULL,
  `order_no` varchar(50) DEFAULT NULL
) ENGINE=MyISAM DEFAULT CHARSET=utf8",

"rpro_out_customers" => "CREATE TABLE `rpro_out_customers` (
  `customer_id` int(11) DEFAULT NULL,
  `rpro_cust_sid` varchar(100) NOT NULL DEFAULT '',
  `first_name` varchar(100) NOT NULL DEFAULT '',
  `last_name` varchar(100) NOT NULL DEFAULT '',
  `address1` varchar(200) NOT NULL DEFAULT '',
  `address2` varchar(200) NOT NULL DEFAULT '',
  `city` varchar(200) NOT NULL DEFAULT '',
  `state` varchar(50) DEFAULT NULL,
  `region` varchar(200) NOT NULL DEFAULT '',
  `zip` varchar(20) NOT NULL DEFAULT '',
  `country` varchar(200) NOT NULL DEFAULT '',
  `country_code` varchar(20) NOT NULL DEFAULT '',
  `phone` varchar(30) NOT NULL DEFAULT '',
  `email` varchar(100) NOT NULL DEFAULT '',
  `login_id` varchar(100) DEFAULT NULL,
  `PASSWORD` varchar(100) DEFAULT NULL,
  `orders_num` int(11) DEFAULT NULL,
  `has_so` int(11) DEFAULT NULL,
  `company` varchar(100) DEFAULT NULL
) ENGINE=MyISAM DEFAULT CHARSET=utf8",

"rpro_out_so" => "CREATE TABLE `rpro_out_so` (
  `orderid` int(12) NOT NULL,
  `so_sid` varchar(64) DEFAULT '',
  `sbs_no` varchar(10) DEFAULT '1',
  `store_no` varchar(10) DEFAULT '1',
  `station` varchar(10) DEFAULT '1',
  `so_no` varchar(64) DEFAULT '',
  `so_type` varchar(10) DEFAULT '0',
  `orig_store_no` varchar(10) DEFAULT '1',
  `orig_station` varchar(10) DEFAULT '1',
  `trgt_store_no` varchar(10) DEFAULT '1',
  `trgt_station` varchar(10) DEFAULT '1',
  `cust_sid` varchar(64) DEFAULT '',
  `addr_no` varchar(10) DEFAULT '1',
  `shipto_cust_sid` varchar(64) DEFAULT '',
  `shipto_addr_no` varchar(10) DEFAULT '1',
  `cust_po_no` varchar(64) DEFAULT '',
  `status` varchar(10) DEFAULT '2',
  `priority` varchar(10) DEFAULT '1',
  `use_vat` varchar(10) DEFAULT '0',
  `disc_perc` varchar(12) DEFAULT '',
  `disc_amt` varchar(12) DEFAULT '',
  `disc_perc_spread` varchar(12) DEFAULT '',
  `used_disc_amt` varchar(12) DEFAULT '',
  `over_tax_perc` varchar(12) DEFAULT '',
  `over_tax_perc2` varchar(12) DEFAULT '',
  `created_date` varchar(32) DEFAULT '',
  `modified_date` varchar(32) DEFAULT '',
  `shipping_date` varchar(32) DEFAULT '',
  `cancel_date` varchar(32) DEFAULT '',
  `note` varchar(255) DEFAULT '',
  `ref_so_sid` varchar(64) DEFAULT '',
  `cms` varchar(10) DEFAULT '1',
  `active` varchar(10) DEFAULT '1',
  `verified` varchar(10) DEFAULT '0',
  `held` varchar(10) DEFAULT '0',
  `cms_post_date` varchar(32) DEFAULT '',
  `pkg_no` varchar(10) DEFAULT '',
  `doc_source` varchar(10) DEFAULT '0',
  `controller` varchar(10) DEFAULT '1',
  `orig_controller` varchar(10) DEFAULT '1',
  `elapsed_time` varchar(10) DEFAULT '1',
  `line_pos_seq` varchar(10) DEFAULT '2',
  `used_subtotal` varchar(12) DEFAULT '',
  `used_tax` varchar(12) DEFAULT '',
  `activity_perc` varchar(12) DEFAULT '100',
  `activity_perc2` varchar(12) DEFAULT '',
  `activity_perc3` varchar(12) DEFAULT '',
  `activity_perc4` varchar(12) DEFAULT '',
  `activity_perc5` varchar(12) DEFAULT '',
  `detax` varchar(10) DEFAULT '0',
  `empl_sbs_no` varchar(10) DEFAULT '1',
  `empl_name` varchar(64) DEFAULT 'SYSADMIN',
  `ship_method` varchar(64) DEFAULT '',
  `tax_area_name` varchar(64) DEFAULT '',
  `tax_area2_name` varchar(64) DEFAULT '',
  `web_so_type` varchar(10) DEFAULT '0',
  `modifiedby_sbs_no` varchar(10) DEFAULT '1',
  `modifiedby_empl_name` varchar(64) DEFAULT 'SYSADMIN',
  `createdby_sbs_no` varchar(10) DEFAULT '1',
  `createdby_empl_name` varchar(64) DEFAULT 'SYSADMIN',
  `clerk_sbs_no` varchar(10) DEFAULT '1',
  `clerk_name` varchar(64) DEFAULT 'SYSADMIN',
  `clerk_sbs_no2` varchar(10) DEFAULT '',
  `clerk_name2` varchar(64) DEFAULT '',
  `clerk_sbs_no3` varchar(10) DEFAULT '',
  `clerk_name3` varchar(64) DEFAULT '',
  `clerk_sbs_no4` varchar(10) DEFAULT '',
  `clerk_name4` varchar(64) DEFAULT '',
  `clerk_sbs_no5` varchar(10) DEFAULT '',
  `clerk_name5` varchar(64) DEFAULT '',
  `customer_cust_sid` varchar(64) DEFAULT '',
  `customer_cust_id` varchar(64) DEFAULT '',
  `customer_store_no` varchar(10) DEFAULT '1',
  `customer_station` varchar(10) DEFAULT '',
  `customer_first_name` varchar(255) DEFAULT '',
  `customer_last_name` varchar(255) DEFAULT '',
  `customer_price_lvl` varchar(10) DEFAULT '',
  `customer_detax` varchar(10) DEFAULT '0',
  `customer_info1` varchar(255) DEFAULT '',
  `customer_info2` varchar(255) DEFAULT '',
  `customer_modified_date` varchar(32) DEFAULT '',
  `customer_sbs_no` varchar(10) DEFAULT '1',
  `customer_cms` varchar(10) DEFAULT '1',
  `customer_company_name` varchar(255) DEFAULT '',
  `customer_title` varchar(64) DEFAULT '',
  `customer_tax_area_name` varchar(64) DEFAULT '',
  `customer_shipping` varchar(10) DEFAULT '0',
  `customer_address1` varchar(255) DEFAULT '',
  `customer_address2` varchar(255) DEFAULT '',
  `customer_address3` varchar(255) DEFAULT '',
  `customer_address4` varchar(255) DEFAULT '',
  `customer_address5` varchar(255) DEFAULT '',
  `customer_address6` varchar(255) DEFAULT '',
  `customer_zip` varchar(64) DEFAULT '',
  `customer_phone1` varchar(64) DEFAULT '',
  `customer_phone2` varchar(64) DEFAULT '',
  `customer_email` varchar(128) DEFAULT '',
  `customer_country_name` varchar(255) DEFAULT 'UNITED STATES',
  `shipto_customer_cust_sid` varchar(64) DEFAULT '',
  `shipto_customer_cust_id` varchar(64) DEFAULT '',
  `shipto_customer_store_no` varchar(10) DEFAULT '1',
  `shipto_customer_station` varchar(10) DEFAULT '',
  `shipto_customer_first_name` varchar(255) DEFAULT '',
  `shipto_customer_last_name` varchar(255) DEFAULT '',
  `shipto_customer_price_lvl` varchar(10) DEFAULT '',
  `shipto_customer_detax` varchar(10) DEFAULT '0',
  `shipto_customer_info1` varchar(255) DEFAULT '',
  `shipto_customer_info2` varchar(255) DEFAULT '',
  `shipto_customer_modified_date` varchar(32) DEFAULT '',
  `shipto_customer_sbs_no` varchar(10) DEFAULT '1',
  `shipto_customer_cms` varchar(10) DEFAULT '1',
  `shipto_customer_company_name` varchar(255) DEFAULT '',
  `shipto_customer_title` varchar(64) DEFAULT '',
  `shipto_customer_tax_area_name` varchar(64) DEFAULT '',
  `shipto_customer_shipping` varchar(10) DEFAULT '0',
  `shipto_customer_address1` varchar(255) DEFAULT '',
  `shipto_customer_address2` varchar(255) DEFAULT '',
  `shipto_customer_address3` varchar(255) DEFAULT '',
  `shipto_customer_address4` varchar(255) DEFAULT '',
  `shipto_customer_address5` varchar(255) DEFAULT '',
  `shipto_customer_address6` varchar(255) DEFAULT '',
  `shipto_customer_zip` varchar(64) DEFAULT '',
  `shipto_customer_phone1` varchar(64) DEFAULT '',
  `shipto_customer_phone2` varchar(64) DEFAULT '',
  `shipto_customer_email` varchar(128) DEFAULT '',
  `shipto_customer_country_name` varchar(255) DEFAULT 'UNITED STATES',
  `tender_type` varchar(255) DEFAULT '',
  `cardholder_name` varchar(255) DEFAULT '',
  `crd_name` varchar(255) DEFAULT '',
  `crd_type` varchar(60) DEFAULT NULL,
  `comment1` varchar(60) DEFAULT NULL,
  `comment2` varchar(60) DEFAULT NULL,
  `instruction1` varchar(60) DEFAULT NULL,
  `instruction2` varchar(60) DEFAULT NULL,
  `instruction3` varchar(60) DEFAULT NULL,
  `instruction4` varchar(60) DEFAULT NULL,
  `instruction5` varchar(60) DEFAULT NULL,
  `pos_flag_1` varchar(60) DEFAULT NULL,
  `pos_flag_2` varchar(60) DEFAULT NULL,
  `pos_flag_3` varchar(60) DEFAULT NULL,
  `currency_name` varchar(64) DEFAULT 'DOLLARS',
  `tender_taken` varchar(64) DEFAULT '',
  `shipping_amt` varchar(255) DEFAULT '',
  `shipping_tax` varchar(255) DEFAULT '',
  PRIMARY KEY (`orderid`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8",

"rpro_out_so_items" => "CREATE TABLE `rpro_out_so_items` (
  `itemid` int(12) NOT NULL AUTO_INCREMENT,
  `orderid` int(12) DEFAULT NULL,
  `so_sid` varchar(64) DEFAULT '',
  `item_sid` varchar(64) DEFAULT '',
  `item_pos` int(12) DEFAULT '1',
  `orig_price` decimal(12,4) DEFAULT '0.0000',
  `orig_tax_amt` decimal(12,4) DEFAULT '0.0000',
  `price` decimal(12,4) DEFAULT '0.0000',
  `cost` decimal(12,4) DEFAULT '0.0000',
  `tax_code` varchar(10) DEFAULT '0',
  `tax_perc` decimal(12,4) DEFAULT '0.0000',
  `tax_amt` decimal(12,4) DEFAULT '0.0000',
  `tax_code2` varchar(10) DEFAULT '0',
  `tax_perc2` varchar(10) DEFAULT '0',
  `tax_amt2` decimal(12,4) DEFAULT '0.0000',
  `ord_qty` int(12) DEFAULT '0',
  `sent_qty` int(12) DEFAULT '0',
  `price_lvl` varchar(10) DEFAULT '1',
  `sched_no` varchar(10) DEFAULT '',
  `comm_code` varchar(10) DEFAULT '-1',
  `spif` varchar(32) DEFAULT '',
  `scan_upc` varchar(128) DEFAULT '',
  `serial_no` varchar(128) DEFAULT '',
  `lot_number` varchar(32) DEFAULT '',
  `kit_flag` varchar(10) DEFAULT '1',
  `pkg_item_sid` varchar(64) DEFAULT '',
  `pkg_seq_no` varchar(32) DEFAULT '',
  `orig_cmpnt_item_sid` varchar(64) DEFAULT '',
  `detax` varchar(10) DEFAULT '0',
  `usr_disc_perc` decimal(12,4) DEFAULT '0.0000',
  `shipto_cust_sid` varchar(64) DEFAULT '',
  `shipto_addr_no` varchar(10) DEFAULT '',
  `pkg_no` varchar(32) DEFAULT '',
  `udf_value1` varchar(255) DEFAULT '',
  `udf_value2` varchar(255) DEFAULT '',
  `udf_value3` varchar(255) DEFAULT '',
  `udf_value4` varchar(255) DEFAULT '',
  `activity_perc` varchar(4) DEFAULT '100',
  `activity_perc1` varchar(4) DEFAULT '',
  `activity_perc2` varchar(4) DEFAULT '',
  `activity_perc3` varchar(4) DEFAULT '',
  `activity_perc4` varchar(4) DEFAULT '',
  `activity_perc5` varchar(4) DEFAULT '',
  `orig_item_pos` int(12) DEFAULT '1',
  `promo_flag` varchar(10) DEFAULT '0',
  `item_note1` varchar(255) DEFAULT '',
  `item_note2` varchar(255) DEFAULT '',
  `item_note3` varchar(255) DEFAULT '',
  `item_note4` varchar(255) DEFAULT '',
  `item_note5` varchar(255) DEFAULT '',
  `item_note6` varchar(255) DEFAULT '',
  `item_note7` varchar(255) DEFAULT '',
  `item_note8` varchar(255) DEFAULT '',
  `item_note9` varchar(255) DEFAULT '',
  `item_note10` varchar(255) DEFAULT '',
  `alt_upc` varchar(128) DEFAULT '',
  `alt_alu` varchar(128) DEFAULT '',
  `alt_cost` decimal(12,4) DEFAULT '0.0000',
  `alt_vend_code` varchar(64) DEFAULT '',
  `empl_sbs_no` varchar(10) DEFAULT '1',
  `empl_name` varchar(64) DEFAULT 'SYSADMIN',
  `tax_area2_name` varchar(64) DEFAULT '',
  `disc_reason_name` varchar(128) DEFAULT '',
  `empl_sbs_no2` varchar(10) DEFAULT '',
  `empl_name2` varchar(64) DEFAULT '',
  `empl_sbs_no3` varchar(10) DEFAULT '',
  `empl_name3` varchar(64) DEFAULT '',
  `empl_sbs_no4` varchar(10) DEFAULT '',
  `empl_name4` varchar(64) DEFAULT '',
  `empl_sbs_no5` varchar(10) DEFAULT '',
  `empl_name5` varchar(64) DEFAULT '',
  `ship_method` varchar(64) DEFAULT '',
  PRIMARY KEY (`itemid`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8",
	"rpro_out_returns" => "CREATE TABLE `rpro_out_returns` (
  `orderid` varchar(20) NOT NULL,
  `so_sid` varchar(32) DEFAULT NULL,
  `comment1` varchar(50) DEFAULT NULL,
  `so_no` varchar(20) DEFAULT NULL,
  `tracking_no` varchar(50) DEFAULT NULL,
  `shipping_tax` varchar(20) DEFAULT '0.0000',
  `shipping_amt` varchar(20) DEFAULT '0.0000',
  `customer_shipping` varchar(20) DEFAULT NULL,
  `clerk_name5` varchar(64) DEFAULT NULL,
  `clerk_sbs_no5` varchar(10) DEFAULT NULL,
  `clerk_name4` varchar(64) DEFAULT NULL,
  `clerk_sbs_no4` varchar(10) DEFAULT NULL,
  `clerk_name3` varchar(64) DEFAULT NULL,
  `clerk_sbs_no3` varchar(10) DEFAULT NULL,
  `clerk_name2` varchar(64) DEFAULT NULL,
  `clerk_sbs_no2` varchar(10) DEFAULT NULL,
  `clerk_name` varchar(64) DEFAULT NULL,
  `clerk_sbs_no` varchar(10) DEFAULT NULL,
  `createdby_empl_name` varchar(64) DEFAULT NULL,
  `createdby_sbs_no` varchar(10) DEFAULT NULL,
  `modifiedby_empl_name` varchar(64) DEFAULT NULL,
  `modifiedby_sbs_no` varchar(10) DEFAULT NULL,
  `web_so_type` varchar(10) DEFAULT NULL,
  `tax_area2_name` varchar(64) DEFAULT NULL,
  `tax_area_name` varchar(64) DEFAULT NULL,
  `ship_method` varchar(20) DEFAULT NULL,
  `empl_name` varchar(64) DEFAULT NULL,
  `empl_sbs_no` varchar(10) DEFAULT NULL,
  `detax` varchar(10) DEFAULT NULL,
  `activity_perc5` varchar(10) DEFAULT NULL,
  `activity_perc4` varchar(10) DEFAULT NULL,
  `activity_perc3` varchar(10) DEFAULT NULL,
  `activity_perc2` varchar(10) DEFAULT NULL,
  `activity_perc` varchar(10) DEFAULT NULL,
  `used_tax` varchar(12) DEFAULT NULL,
  `used_subtotal` varchar(12) DEFAULT NULL,
  `line_pos_seq` varchar(10) DEFAULT NULL,
  `elapsed_time` varchar(10) DEFAULT NULL,
  `orig_controller` varchar(10) DEFAULT NULL,
  `controller` varchar(10) DEFAULT NULL,
  `doc_source` varchar(10) DEFAULT NULL,
  `pkg_no` varchar(10) DEFAULT NULL,
  `cms_post_date` varchar(32) DEFAULT NULL,
  `held` varchar(10) DEFAULT NULL,
  `verified` varchar(10) DEFAULT NULL,
  `active` varchar(10) DEFAULT NULL,
  `cms` varchar(10) DEFAULT NULL,
  `ref_so_sid` varchar(20) DEFAULT NULL,
  `note` varchar(255) DEFAULT NULL,
  `cancel_date` varchar(32) DEFAULT NULL,
  `shipping_date` varchar(32) DEFAULT NULL,
  `modified_date` varchar(32) DEFAULT NULL,
  `created_date` varchar(32) DEFAULT NULL,
  `over_tax_perc2` varchar(10) DEFAULT NULL,
  `over_tax_perc` varchar(10) DEFAULT NULL,
  `used_disc_amt` varchar(12) DEFAULT NULL,
  `disc_perc_spread` varchar(10) DEFAULT NULL,
  `disc_amt` varchar(10) DEFAULT '0.0000',
  `disc_perc` varchar(10) DEFAULT '0.0000',
  `use_vat` varchar(10) DEFAULT NULL,
  `priority` varchar(10) DEFAULT NULL,
  `status` varchar(10) DEFAULT NULL,
  `cust_po_no` varchar(32) DEFAULT NULL,
  `shipto_addr_no` varchar(10) DEFAULT NULL,
  `shipto_cust_sid` varchar(32) DEFAULT NULL,
  `addr_no` varchar(10) DEFAULT NULL,
  `cust_sid` varchar(32) DEFAULT NULL,
  `trgt_station` varchar(10) DEFAULT NULL,
  `trgt_store_no` varchar(10) DEFAULT NULL,
  `orig_station` varchar(10) DEFAULT NULL,
  `orig_store_no` varchar(10) DEFAULT NULL,
  `so_type` varchar(10) DEFAULT NULL,
  `station` varchar(10) DEFAULT NULL,
  `store_no` varchar(10) DEFAULT NULL,
  `sbs_no` varchar(10) DEFAULT NULL,
  `pos_flag_1` varchar(60) DEFAULT NULL,
  `pos_flag_2` varchar(60) DEFAULT NULL,
  `pos_flag_3` varchar(60) DEFAULT NULL,
  PRIMARY KEY (`orderid`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1",
"rpro_out_returns_items"=>"CREATE TABLE `rpro_out_returns_items` (
  `orderid` varchar(20) DEFAULT NULL,
  `item_sid` varchar(20) DEFAULT NULL,
  `item_pos` varchar(20) DEFAULT NULL,
  `orig_price` varchar(20) DEFAULT NULL,
  `orig_tax_amt` varchar(20) DEFAULT NULL,
  `price` varchar(20) DEFAULT NULL,
  `cost` varchar(20) DEFAULT NULL,
  `tax_code` varchar(20) DEFAULT NULL,
  `tax_perc` varchar(20) DEFAULT NULL,
  `tax_amt` varchar(20) DEFAULT NULL,
  `tax_code2` varchar(20) DEFAULT NULL,
  `tax_perc2` varchar(20) DEFAULT NULL,
  `tax_amt2` varchar(20) DEFAULT NULL,
  `ord_qty` varchar(20) DEFAULT NULL,
  `sent_qty` varchar(20) DEFAULT NULL,
  `price_lvl` varchar(20) DEFAULT NULL,
  `comm_code` varchar(20) DEFAULT NULL,
  `kit_flag` varchar(20) DEFAULT NULL,
  `detax` varchar(20) DEFAULT NULL,
  `usr_disc_perc` varchar(20) DEFAULT NULL,
  `activity_perc` varchar(20) DEFAULT NULL,
  `promo_flag` varchar(20) DEFAULT NULL,
  `alt_cost` varchar(20) DEFAULT NULL,
  `empl_sbs_no` varchar(20) DEFAULT NULL,
  `empl_name` varchar(20) DEFAULT NULL,
  `tax_area2_name` varchar(20) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1",
                             );
							 
	public static $pos_views = array(
	"rpro_in_prices" => "
CREATE VIEW `rpro_in_prices` AS 
(SELECT 
  `rpro_in_items`.`style_sid` AS `style_sid`,
  MIN(`rpro_in_items`.`reg_price`) AS `reg_price`,
  MIN(`rpro_in_items`.`cost`) AS `cost`,
  MIN(`rpro_in_items`.`sale_price`) AS `sale_price`,
  MIN(`rpro_in_items`.`msrp_price`) AS `msrp_price`,
  MIN(
    `rpro_in_items`.`wholesale_price`
  ) AS `wholesale_price` 
FROM
  `rpro_in_items` 
WHERE (`rpro_in_items`.`excluded` = 0) 
GROUP BY `rpro_in_items`.`style_sid`)",
	"rpro_in_prices_priceqty" => "CREATE VIEW `rpro_in_prices_priceqty` AS 
(SELECT 
  `rpro_in_priceqty`.`style_sid` AS `style_sid`,
  MIN(`rpro_in_priceqty`.`reg_price`) AS `reg_price`,
  MIN(`rpro_in_priceqty`.`cost`) AS `cost`,
  MIN(
    `rpro_in_priceqty`.`sale_price`
  ) AS `sale_price`,
  MIN(
    `rpro_in_priceqty`.`msrp_price`
  ) AS `msrp_price`,
  MIN(
    `rpro_in_priceqty`.`wholesale_price`
  ) AS `wholesale_price` 
FROM
  `rpro_in_priceqty` 
GROUP BY `rpro_in_priceqty`.`style_sid`)"
	);
    
}

?>
