<?php
/**
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End User Software Agreement (EULA).
 * It is also available through the world-wide-web at this URL:
 * http://www.harapartners.com/license
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to eula@harapartners.com so we can send you a copy immediately.
 * 
 */
?>

<?php $_code=$this->getMethodCode() ?>
<?php $_customerId = Mage::getSingleton('adminhtml/session_quote')->getCustomerId() ?>
<ul class="form-list" id="payment_form_<?php echo $_code ?>" style="display:none;">
	<?php if($_customerId && $_profiles = $this->getProfileInfo($_customerId)): ?>
	<li class="switch-card-control">
        <label for="<?php echo $_code ?>_payment_profiles"><?php echo $this->__('Choose Credit Card') ?></label>
        <div class="input-box">
            <select id="<?php echo $_code ?>_payment_profiles" name="payment[payment_profile]">
            	<option value=""><?php echo $this->__('New Credit Card') ?></option>
            <?php foreach ($_profiles as $_profile): ?>
                <option value="<?php echo $_profile['encodedPaymentProfileId'] ?>"><?php echo 'xxxx-' . $_profile['last4digits'] ?></option>
            <?php endforeach ?>
            </select>
        </div>
    </li>
    <?php endif ?>
    <div class="use-new-card-wrapper">
	    <li>
	        <label for="<?php echo $_code ?>_cc_type"><?php echo $this->__('Credit Card') ?><em class="required">*</em></label>
	        <div class="input-box">
	            <select id="<?php echo $_code ?>_cc_type" name="payment[cc_type]" class="required-entry validate-cc-type-select">
	                <option value=""><?php echo $this->__('--Please Select--')?></option>
	            <?php $_ccType = $this->getInfoData('cc_type') ?>
	            <?php foreach ($this->getCcAvailableTypes() as $_typeCode => $_typeName): ?>
	                <option value="<?php echo $_typeCode ?>"<?php if($_typeCode==$_ccType): ?> selected="selected"<?php endif ?>><?php echo $_typeName ?></option>
	            <?php endforeach ?>
	            </select>
	        </div>
	    </li>
	    <li>
	        <label for="<?php echo $_code ?>_cc_number"><?php echo $this->__('Credit Card Number') ?><em class="required">*</em></label>
	        <div class="input-box">
	            <input type="text" id="<?php echo $_code ?>_cc_number" name="payment[cc_number]" title="<?php echo $this->__('Credit Card Number') ?>" class="input-text validate-cc-number validate-cc-type" value="" autocomplete="off"/>
	        </div>
	    </li>
	    <li id="<?php echo $_code ?>_cc_type_exp_div">
	        <label for="<?php echo $_code ?>_expiration"><?php echo $this->__('Expiration Date') ?><em class="required">*</em></label>
	        <div class="input-box">
                <select id="<?php echo $_code ?>_expiration" name="payment[cc_exp_month]" class="month validate-cc-exp required-entry">
                <?php $_ccExpMonth = $this->getInfoData('cc_exp_month') ?>
                <?php foreach ($this->getCcMonths() as $k=>$v): ?>
                    <option value="<?php echo $k?$k:'' ?>"<?php if($k==$_ccExpMonth): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
                <?php endforeach ?>
                </select>
                <?php $_ccExpYear = $this->getInfoData('cc_exp_year') ?>
                <select id="<?php echo $_code ?>_expiration_yr" name="payment[cc_exp_year]" class="year required-entry">
                <?php foreach ($this->getCcYears() as $k=>$v): ?>
                    <option value="<?php echo $k?$k:'' ?>"<?php if($k==$_ccExpYear): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
                <?php endforeach ?>
                </select>
	        </div>
	    </li>
	    <?php if($this->hasVerification()): ?>
	    <li id="<?php echo $_code ?>_cc_type_cvv_div">
	        <label for="<?php echo $_code ?>_cc_cid"><em class="required">*</em><?php echo $this->__('Card Verification Number') ?></label>
	        <div class="input-box">
	            <div class="v-fix">
	                <input type="text" title="<?php echo $this->__('Card Verification Number') ?>" class="input-text cvv required-entry validate-cc-cvn" id="<?php echo $_code ?>_cc_cid" name="payment[cc_cid]" value="" autocomplete="off"/>
	            </div>
	            <a href="#" class="cvv-what-is-this"><?php echo $this->__('What is this?') ?></a>
	        </div>
	    </li>
	    <?php endif; ?>
	    <?php if($_customerId): ?>
	    <li id="<?php echo $_code ?>_save_cc">
	        <label for="<?php echo $_code ?>_save_cc"><?php echo $this->__('Save This Card') ?></label>
            <input type="checkbox" title="<?php echo $this->__('Save This Card') ?>" id="<?php echo $_code ?>_save_cc" name="payment[save_cc]" value="1" />
	    </li>
	    <?php endif ?>
	
	    <?php if ($this->hasSsCardType()): ?>
	    <li id="<?php echo $_code ?>_cc_type_ss_div">
	        <ul class="inner-form">
	            <li class="form-alt"><label for="<?php echo $_code ?>_cc_issue"><em class="required">*</em><?php echo $this->__('Switch/Solo/Maestro Only') ?></label></li>
	            <li>
	                <label for="<?php echo $_code ?>_cc_issue"><?php echo $this->__('Issue Number') ?>:</label>
	                <span class="input-box">
	                    <input type="text" title="<?php echo $this->__('Issue Number') ?>" class="input-text validate-cc-ukss cvv" id="<?php echo $_code ?>_cc_issue" name="payment[cc_ss_issue]" value="" />
	                </span>
	            </li>
	            <li>
	                <label for="<?php echo $_code ?>_start_month"><?php echo $this->__('Start Date') ?>:</label>
	                <div class="input-box">
                        <select id="<?php echo $_code ?>_start_month" name="payment[cc_ss_start_month]" class="validate-cc-ukss month">
                        <?php foreach ($this->getCcMonths() as $k=>$v): ?>
                            <option value="<?php echo $k?$k:'' ?>"<?php if($k==$this->getInfoData('cc_ss_start_month')): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
                        <?php endforeach ?>
                        </select>
                        <select id="<?php echo $_code ?>_start_year" name="payment[cc_ss_start_year]" class="validate-cc-ukss year">
                        <?php foreach ($this->getSsStartYears() as $k=>$v): ?>
                            <option value="<?php echo $k?$k:'' ?>"<?php if($k==$this->getInfoData('cc_ss_start_year')): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
                        <?php endforeach ?>
                        </select>
	                </div>
	            </li>
	            <li class="adv-container">&nbsp;</li>
	        </ul>
	        <script type="text/javascript">
	        //<![CDATA[
	        var SSChecked<?php echo $_code ?> = function() {
	            var elm = $('<?php echo $_code ?>_cc_type');
	            if (['SS','SM','SO'].indexOf(elm.value) != -1) {
	                $('<?php echo $_code ?>_cc_type_ss_div').show();
	            } else {
	                $('<?php echo $_code ?>_cc_type_ss_div').hide();
	            }
	        };
	
	        Event.observe($('<?php echo $_code ?>_cc_type'), 'change', SSChecked<?php echo $_code ?>);
	        SSChecked<?php echo $_code ?>();
	        //]]>
	        </script>
	    </li>
	    <?php endif; ?>
    </div>
</ul>
<script type="text/javascript">
jQuery(document).ready(function() {
	var newCardWrap = jQuery('.use-new-card-wrapper');
	var newCardCtrls = newCardWrap.find('input, select');
    jQuery('select#authorizenetcim_payment_profiles').change(function() {
        if( jQuery(this).val() == '' ) {
            newCardWrap.show();
            newCardCtrls.removeAttr('disabled');
        } else {
			newCardWrap.hide();
			newCardCtrls.attr('disabled', 'disabled');
        }
    });
});
</script>