<?php $records = count($this->getCollection())?>
<div><b>Total Records : <?php echo $records?></b></div>
<div id="singleSort" style="width:100%;"></div>

<script>
	jQuery(document).ready(function() {
		jQuery("#singleSort").kendoGrid({
	        dataSource: {
	            data: <?php echo $this->getCollectionJson()?>,
	            pageSize: 30
	        },
	        sortable: {
	            mode: "single",
	            allowUnsort: false
	        },
	        pageable: true,
	        scrollable: false,
	        columns: [
	 	        {
	                field: "entity_id",
	                title: "Customer ID",
	                type: "number"
	            },	      	        
	            {
	                field: "firstname",
	                title: "First Name"
	            },
	            {
	                field: "lastname",
	                title: "Last Name"
	            },
	            {
	                field: "email",
	                title: "Email"
	            },
	            {
	                field: "website_name",
	                title: "Website Name"
	            },
	            {
	                field: "store_name",
	                title: "Store Name"
	            },
	            {
	                field: "total_orders",
	                title: "Total Orders",
	                type: "number"
	            },
	            {
	                field: "total_units",
	                title: "Total Units",
	                type: "number"
	            },
	            {
	                field: "total_amount",
	                title: "Total Amount",
		            type: "number"
	            }
	            ,
	            {
	                field: "created_at",
	                title: "Created at"
	            }
	            ,
	            {
	                field: "updated_at",
	                title: "Updated at"
	            }
	        ]
	    });
	 });
</script>