<?php
/**
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End User Software Agreement (EULA).
 * It is also available through the world-wide-web at this URL:
 * http://www.harapartners.com/license
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to eula@harapartners.com so we can send you a copy immediately.
 */
?>
<div class="vendoroptions-body-content">
<?php
	$helper = $this->helper('catalog/output');
	$catalogRootInfoArray = $this->getCatalogRootInfoArray();
?>
<?php if(count($catalogRootInfoArray) == 0): ?>
	<p class="note-msg"><?php echo $this->__('There are no products available for this brand.') ?></p>
<?php else: ?>
	<?php foreach($catalogRootInfoArray as $catalogRootInfo): ?>
		<?php 
			$productCollection = $catalogRootInfo['product_collection'];
			$category = $catalogRootInfo['category_object']; 
		?>
		<div class="category-products">
		    <div class="top-seller-container">
		    	<div class="top-seller-title">Top Seller for <?php echo $category->getName()?></div>
		    	<a class="top-seller-view-all" href="<?php echo $this->getCategoryBrandFilterUrl($category) ;?>">View All</a>
		    </div>
		    <div class="clear"></div>
		    <?php $_collectionSize = $productCollection->count() ?>
		    <?php 
		   		$_columnCount = Harapartners_Service_Helper_Catalog::PRODUCT_LIST_PAGE_GRID_COLUMN_COUNT;
		    ?>
		    <?php $i=0; foreach ($productCollection as $_product): ?>
		        <?php if ($i++%$_columnCount==0): ?>
		        <ul class="products-grid">
		        <?php endif ?>
		            <li class="item<?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?>">
		                <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(150); ?>" width="150" height="150" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
		                <?php echo $this->getReviewsSummaryHtml($_product, 'hp_grid', true) ?>
		                <h1 class='product-brand'><?php echo $_product->getVendorName(); ?></h1>
		                <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h2>
		                <?php echo $this->getPriceHtml($_product, true) ?>
		            </li>
		        <?php if ($i%$_columnCount==0 || $i==$_collectionSize): ?>
		        </ul>
		        <?php endif ?>
		    <?php endforeach ?>
			<script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd','even','first','last'])</script>
		</div>
	<?php endforeach; ?>
<?php endif; ?>
</div>